package backend.academy;

import backend.academy.Generators.EntityGenerators.BasicEntityGenerator;
import backend.academy.Generators.MazeGenerators.KrascalMazeGenerator;
import backend.academy.Generators.MazeGenerators.KrascalWithExtraEdges;
import backend.academy.Generators.MazeGenerators.PrimMazeGenerator;
import backend.academy.MazeClasses.Maze;
import backend.academy.MazeClasses.Vertex;
import backend.academy.Renderers.ConsoleMazeRenderer;
import backend.academy.Solvers.AStarMazeSolver;
import backend.academy.Solvers.BFSMazeSolver;
import backend.academy.Solvers.DijkstraMazeSolver;
import java.io.IOException;
import java.io.PrintStream;
import java.util.Scanner;
import lombok.experimental.UtilityClass;

@UtilityClass
public class Application {
    private final PrintStream out = System.out;
    private final int maxSize = 100;

    public static void main(String[] args) throws IOException {
        int width = getNum(2, maxSize, "Width");
        int height = getNum(2, maxSize, "Height");
        int startX = getNum(0, width - 1, "Start X");
        int startY = getNum(0, height - 1, "Start Y");
        int endX = getNum(0, width - 1, "End X");
        int endY = getNum(0, height - 1, "End Y");
        out.println();

        Maze maze = new Maze(width, height);
        maze.generateEntities(new BasicEntityGenerator());
        maze.setStart(new Vertex(startX, startY));
        maze.setEnd(new Vertex(endX, endY));

        maze.generateEdges(new PrimMazeGenerator());
        maze.solve(new BFSMazeSolver());
        out.println("Generated by Prim algorythm, solved by BFS algorythm:");
        maze.showSolution(new ConsoleMazeRenderer());
        out.println();

        maze.generateEdges(new KrascalMazeGenerator());
        maze.solve(new DijkstraMazeSolver());
        out.println("Generated by Krascal algorythm, solved by Dijkstra algorythm:");
        maze.showSolution(new ConsoleMazeRenderer());
        out.println();

        maze.generateEdges(new KrascalWithExtraEdges());
        maze.solve(new AStarMazeSolver());
        out.println("Generated by Krascal algorythm with adding extra edges, solved by A* algorythm:");
        maze.showSolution(new ConsoleMazeRenderer());
        out.println();
    }

    private int getNum(int min, int max, String name) {
        int k;
        Scanner scanner = new Scanner(System.in);
        out.println(String.format("Please enter %s (from %d to %d): ", name, min, max));
        while (true) {
            k = scanner.nextInt();
            if (k >= min && k <= max) {
                break;
            }
            out.println(String.format("From %d to %d! Try again!", min, max));
        }
        return k;
    }
}
